replicaCount: 1

image:
  repository: ghcr.io/open-webui/open-webui
  tag: v0.5.16
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: open-webui.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

persistence:
  enabled: true
  size: 10Gi
  storageClass: ""

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2
    memory: 3Gi

env:
  WEBUI_AUTH: "False"
  ENABLE_RAG_WEB_SEARCH: "True"